[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
[functions]
  node_bundler = "nft"
  external_node_modules = ["vite", "lightningcss"]